services:
    lis:
        build:
            context: . # 👈 Reuse your real Dockerfile
        working_dir: /app
        env_file: .env
        environment:
            POSTGRES_URI: postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable
            MILVUS_URI: http://milvus:19530 # <<<<<< explicit overwrite for lis service
            DATA_DIR: /app/data
            PROMPTS_DIR: /app/prompts
            API_URL: http://localhost:8000
        ports:
            - "8000:8000" # Backend
            - "8501:8501" # Frontend
        networks:
            - net
        depends_on:
            - postgres
            - milvus
        volumes:
            - .:/app # 👈 mount entire project into container for live reload
        command: /bin/bash -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload & streamlit run frontend.py --server.port 8501 --server.address 0.0.0.0"

    postgres:
        image: postgres:17
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        networks:
            - net

    etcd:
        image: quay.io/coreos/etcd:v3.5.18
        environment:
            - ETCD_AUTO_COMPACTION_MODE=revision
            - ETCD_AUTO_COMPACTION_RETENTION=1000
            - ETCD_QUOTA_BACKEND_BYTES=4294967296
        command: etcd -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
        networks:
            - net

    minio:
        image: minio/minio:RELEASE.2024-12-18T13-15-44Z
        environment:
            MINIO_ACCESS_KEY: minioadmin
            MINIO_SECRET_KEY: minioadmin
        command: minio server /minio_data
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
        networks:
            - net

    milvus:
        image: milvusdb/milvus:v2.6.0
        command: ["milvus", "run", "standalone"]
        environment:
            ETCD_ENDPOINTS: etcd:2379
            MINIO_ADDRESS: minio:9000
        ports:
            - "19530:19530"
            - "19121:19121" # Optional, REST API
        depends_on:
            - etcd
            - minio
        networks:
            - net
        volumes:
            - lis_milvus:/var/lib/milvus

volumes:
    lis_milvus:

networks:
    net:
